Adding the i18n keys for the voucher status
ourjapanlife/findadoc-localization pull request #68
Opened 2021-06-26 21:46 UTC by JohnTitor2036

### Screenshots

English
![image](https://user-images.githubusercontent.com/35844978/123526372-6e18d080-d6a5-11eb-8671-727153f22e1d.png)

French
![image](https://user-images.githubusercontent.com/35844978/123526375-6fe29400-d6a5-11eb-891c-cb516a6b687e.png)

2021-06-26 21:48 UTC, JohnTitor2036 commented
Needed for the [pull request #175 of the frontend project](https://github.com/ourjapanlife/findadoc-frontend/pull/175) :)

2021-06-26 23:26 UTC, theyokohamalife requested changes
Thank you for doing this so quickly! Just a couple small changes requested.

2021-06-26 23:26 UTC, theyokohamalife commented on locales/en.json
> +            "required" : "Required",
Can you remove the space before the colon? Example: `"required":  "Required",`

2021-06-26 23:26 UTC, theyokohamalife commented on locales/en.json
> +            "notRequired" : "Not Required"
Please remove the space here too.

2021-06-27 12:56 UTC, JohnTitor2036 commented
I've removed the extra space, thank you!

2021-06-27 14:37 UTC, merged

2021-06-27 14:44 UTC, ann-kilzer reviewed
LGTM 🌟

2021-06-27 14:49 UTC, ann-kilzer commented
Let's make sure to get a review before merging in the future :)

2021-06-27 14:50 UTC, JohnTitor2036 commented
@ann-kilzer My mistake, I'll do that next time.